jobs:
  build-linux-jdk8:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-package: jdk
        java-version: 1.8
    - continue-on-error: true
      name: Install dependencies
      run: sudo apt-get update && sudo apt-get install xvfb
    - continue-on-error: true
      name: Build with Maven
      run: 'cd maven

        xvfb-run -a mvn install

        '
    - continue-on-error: true
      name: Fetch archetype projects
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-name: cn1-maven-archetypes.zip
        file-url: https://github.com/shannah/cn1-maven-archetypes/archive/refs/heads/master.zip
    - continue-on-error: true
      name: Install archetype projects
      run: 'unzip cn1-maven-archetypes.zip

        cd cn1-maven-archetypes-master

        xvfb-run -a mvn install archetype:update-local-catalog

        xvfb-run -a mvn archetype:crawl

        '
    - continue-on-error: true
      name: Run Maven Unit Tests
      run: 'pwd

        xvfb-run -a bash tests/all.sh

        cd maven/integration-tests

        xvfb-run -a bash all.sh

        '
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ant.yml
