jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 1.8
        server-id: nexus-staging
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Set up Git Config
      run: 'git config --global user.name "GitHub Actions Bot"

        git config --global user.email "github-actions@codenameone.com"

        '
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Deploy with Maven
      run: 'cat $HOME/.m2/settings.xml

        cd maven

        bash update-version.sh "$GITHUB_REF_NAME"

        export GPG_TTY=$(tty)

        xvfb-run -a mvn deploy -Psign-artifacts -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE

        cd ..

        git clone https://github.com/shannah/cn1-maven-archetypes

        cd cn1-maven-archetypes

        bash update-version.sh "$GITHUB_REF_NAME"

        xvfb-run -a mvn deploy -Psign-artifacts -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE

        '
name: Release on Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release-on-maven-central.yml
